[package]
name = "spoilers"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[build-dependencies]
cxx-build = "*"

[dependencies]
anyhow = "*"
cxx = "*"
eframe = { version = "*", features = [ "persistence" ] }
egui = "*"
ocrs = "*"
once_cell = "*"
rten = "*"
rten-tensor = "*"
serde = { version = "*", features = [ "derive" ] }
strum = { version = "*", features = [ "derive" ] }
tokenizers = { version = "*", features = [ "http" ] }
toml = "*"
xcap = "*"
