[package]
name = "spoilers"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[build-dependencies]
# bindgen = "*"
cxx-build = "*"

[dependencies]
anyhow = "*"
cxx = "*"
ocrs = "*"
rten = "*"
rten-tensor = "*"
textwrap = "*"
tokenizers = { version = "*", features = [ "http" ] }

# Wait for KDE wayland support and update to crates.io
xcap.github = "https://github.com/nashaofu/xcap"
